### ISSUE TITLE
[ENHANCEMENT] API error description

### ISSUE THREAD

**Issue by fatuuse** [hasl-sensor/integration#11]
It would be nice if API error would be explained with reason:
```
Statuskod | Meddelande
-- | --
1001 | problem with request: Key is undefinedNyckel hare ej skickats med.
1002 | problem with request: Key is invalidNyckel är ogiltig
1003 | Invalid apiOgiltigt api
1004 | problem with request: This api is currently not available for keys with priority above 2
1005 | Nyckel finns, men ej för detta apiproblem with request: Invalid api for key
1006 | To many requests per minuteFör många anrop per minut, för den profil som används
1007 | To many requests per monthFör många anrop per månad, för den profil som används
4001 | SiteId måste gå att konvertera till heltal.
5321 | Kunde varken hämta information från TPI (tunnelbanan) eller DPS (övriga trafikslag).
5322 | Kunde inte hämta information från DPS.
5323 | Kunde inte hämta information från TPI.
5324 | Kunde varken hämta information från TPI (tunnelbanan) eller DPS (övriga trafikslag) p.g.a. inaktuell DPS-data. Detta uppstår om DPS-datan är äldre än 2 minuter vid svarstillfället.

```

from: https://www.trafiklab.se/node/15754/documentation

I had the response 5324. But I think it not because of the integration, but on the server side.

**Comment by DSorlov** [comment]
I am trying to evaluate how much to "fix" the old api as the new is about to be released; but if time permits this is a really good suggestion to make. As for now the new api have been delayed with over six months already so not crossing my fingers on that one yet...

**Comment by DSorlov** [comment]
The API will be replaced by GTFS in future release and this API will be deprecated so will not implement.

**Comment by DSorlov** [comment]
Actually did some improvements by accident after closing this. Still not translating but atleast publishing the raw error message on API failure.
