### ISSUE TITLE
Hasl fails to update sensor on Home Assistant 0.113.3

### ISSUE THREAD

**Issue by leikoilja** [hasl-sensor/integration#2]
There is an error message in the logs saying:

![image](https://user-images.githubusercontent.com/10655107/89899441-98bf7f00-dbe2-11ea-8555-71095c1aa9a1.png)

Although it did work for me with a previous HA version.

**Comment by DSorlov** [comment]
Which line was this? Relevant settings block would help me track this down.

**Comment by DSorlov** [comment]
No response and not reproducible. Will close.
