### ISSUE TITLE
Wrong in required HA version vs installed during installation of HASL 3.0.1

### ISSUE THREAD

**Issue by Baeckman** [hasl-sensor/integration#26]
Trying to install HASLv3 (3.0.1) via HACS but version check is wrong. My installed HA is 2021.12.0 and the required version is 2021.12 according to HASL. Should be ok but get error during install. I huess it is the ".0" that is causing the problem.

Running versions
HA: 2021.12.0
HACS: 1.19.3
HASLv3: 3.0.0, 3.0.0 or master tested

hacs.json does say "2021.12" as HA version. Maybe change that to "2021.12.0" instead?

**Comment by Baeckman** [comment]
![hasl_error_text](https://user-images.githubusercontent.com/61110362/149129433-e321fc6b-0c8d-4426-8e04-5808321a9cdb.jpeg)
![hasl_error](https://user-images.githubusercontent.com/61110362/149129442-e11056f6-87a9-4064-ab0c-54a6962efb77.jpeg)

**Comment by DSorlov** [comment]
@Baeckman have you got it to work? Once installed you need to go to the integrations page and add the HASL integration there. You will create one integration for each sensor. After you create the sensor you click the configure link to set the parameters for the sensor.
