### ISSUE TITLE
Wrong API mentioned in readme

### ISSUE THREAD

**Issue by mattiasottosson** [hasl-sensor/integration#27]
Hi!

I'm trying this out for the first time and noticed that the readme states:

```
First, visit https://www.trafiklab.se/api and create a free account.

They provide multiple APIs, the ones you want is

"SL Trafikinformation 4"
"SL Störningsinformation 2"
```

However, there's no API called "Trafikinformation 4" and the link goes to [ "Realtidsiformation 4"](https://www.trafiklab.se/api/trafiklab-apis/sl/departures-4/)

<img width="966" alt="Screen Shot 2022-01-13 at 14 04 03" src="https://user-images.githubusercontent.com/616998/149335318-c4c5f4f7-57a7-40f1-8262-c3d18f2be213.png">

I guess it's just a typo?

**Comment by DSorlov** [comment]
Documentation is beeing moved (details) to hasl.sorlov.com, I have fixed the issue there and the next release here it will be removed anyways. Thanks for finding this error! =)
