### ISSUE TITLE
Empty result back from quary

### ISSUE THREAD

**Issue by lawi75** [hasl-sensor/integration#36]
No departures returned from query:

unit_of_measurement: min
api_result: Ok
scan_interval: 300
refresh_enabled: true
attribution: Stockholms Lokaltrafik
departures: []
deviations: []
last_refresh: '2022-03-08 10:29:13'
next_departure_minutes: 4
next_departure_time: '10:34:25'
deviation_count: 0
icon: mdi:train
friendly_name: SL Departure Sensor 3704

**Comment by DSorlov** [comment]
How is the integration configured?

**Comment by hanimayahi** [comment]
I'm also having this issue, I was able to add this integration only after the recent update.

My configuration:
![image](https://user-images.githubusercontent.com/4244349/157488473-adebfbcb-2c70-49f9-a178-48fde8bf563b.png)

Entity:

```
unit_of_measurement: min
api_result: Ok
scan_interval: 300
refresh_enabled: true
attribution: Stockholms Lokaltrafik
departures: []
deviations: []
last_refresh: '2022-03-09 17:36:40'
next_departure_minutes: 0
next_departure_time: '17:40:30'
deviation_count: 0
icon: mdi:train
friendly_name: SL Departure Sensor 1080 (Stockholm City)
```
