### ISSUE TITLE
Bus line directions and name of bus direction

### ISSUE THREAD

**Issue by magune** [hasl-sensor/integration#42]
If I set direction to 1 or 2, it is always reset to 0 whenever I go back to the same config panel:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/50596445/170353114-34ab1505-75f9-484c-9076-c12f0a95ed6d.png">

This means the departure card always shows both directions of my bus line, even though I am only 1 stop from the end station and will never go that direction. I always only go in the direction of the citycentre.

In addition to the problem of seeing 2 directions when I only want to display 1 direction, it is also quite confusing where the bus goes. It apparently displays the end station name, which makes no meaningful sense to me. I know I want to go in the direction of the city center, but the name of the end station far away AFTER the city center has no relevant meaning to me as I am never in that part of the city.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/50596445/170353562-10f9a21c-991d-4980-bb50-9cd0f0cd426a.png">

It would be good to have a configuration property to override the name of the direction, and force it to e.g. "Towards city centre" rather than having the name of the end station that is fairly unknown when you never go there.

**Comment by DSorlov** [comment]
Filtering seems broken; will look into this for release. Huge thanks!

About the naming I will think about implementing something here, but the logic is that the text should correspond to what is on the actual bus (ie when I stand at the stop I will go on the buss that have the correct sign instead of guessing). However this might be possible to configure in the cards. I will have a think and see how to do this. =)

**Comment by magune** [comment]
Thank you!

I completely get the current implementation of naming for many use-cases, in particular if you are at a bus stop with many bus lines.

In my case, we are almost at the end of the line, with only one bus line driving this route. So all busses always are the same bus line number, going in the direction to the citycenter (because we would never take the bus to the end station one stop from here). Since the actual text from the bus is not needed, and due to my dashboard layout, I get 3 lines of text when only one line is needed:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/50596445/170923066-bda594b2-d1d6-4103-96eb-3e58674fca2e.png">

So the text towards "City" would be far more space efficient than "Hisingsängens vändplan (Jönköpings kn)" or similar that the integration feeds me with.

**Comment by DSorlov** [comment]
Fixed in https://github.com/hasl-sensor/lovelace-hasl-departure-card/releases/tag/v2.6.0

**Comment by matrixes** [comment]
I'm having the same issue described in OP, where I can't change the direction after having saved the initial configuration of the sensor. I'm using the latest code from the master branch.
