### ISSUE TITLE
Getting frequent SLAPI_API_Error 5324: None (Departures) errors 

### ISSUE THREAD

**Issue by grobius** [hasl-sensor/integration#45]
Hi,

Just I'm frequently getting SLAPI_API_Error 5324: None (Departures) when polling the API. Just want to know if anyone else is having the same experience. I'm just polling aprox 150 request/day and sometimes it seems to work. 

Thx!

**Comment by DSorlov** [comment]
What lines are you polling? Do you have a departure within 60 minutes?
Are you using the beta version or stable version?

**Comment by grobius** [comment]
Polling line 29 from site 9681 at an interval of 360sec and yes there are almost always departures withing 60min during daytime. I'm running v.3.0.6

**Comment by grobius** [comment]
Seems like issue is fixed now, assume this error was on API side. Thx!
