### ISSUE TITLE
Implement the solution for Skånetrafiken

### ISSUE THREAD

**Issue by Sadoo-MH** [hasl-sensor/integration#46]
Hi,
i was trying to do this but for skånetrafiken and i was not able to do so, since you have wrote on the description that it could be done for whole sweden,
my use case is i just need to see the departure time for a specific buss stop and the train times on the central station, and also if there is any delays that it will show the delay
i hope this is something can be done with this integration since i searched alot for a solution and i couldn't find,

many thanks
All the best!

**Comment by DSorlov** [comment]
Please use beta-version for resrobot support. It is available in HACS
