### ISSUE TITLE
ResRobot v2.1 API not working?

### ISSUE THREAD

**Issue by Strixx76** [hasl-sensor/integration#47]
According to docuymentation there should be two services for locking up a stop ID: rr_find_location and sl_find_location
but there is only one: find_location
If I try to use this service to find a stop ID I get:
SLAPI_API_Error 1002: The supplied API key is not valid (Location Lookup)

So I used a browser instead to get the stop ID, but when I create a sensors with this i get:
SLAPI_API_Error 1002: The supplied API key is not valid (Departures)

Is the ResRobot v2.1 API not implemented?

**Comment by DSorlov** [comment]
Please use beta-version for resrobot support. It is available in HACS
