### ISSUE TITLE
SLAPI_API_Error 5324: None (Departure Board)

### ISSUE THREAD

**Issue by bozman2021** [hasl-sensor/integration#50]
Hi,

I had once successfull integration but had to change locationid and now it's not working at all.
Keep getting 5324.

**Comment by bozman2021** [comment]
This is probably the reason:
https://support.trafiklab.se/org/trafiklabse/d/sl-realtidsinformation-overbelastad/

**Comment by DSorlov** [comment]
Hej. Rekommenderar att du kollar på att använda ResRobot-sensorn i integrationen. Lade till den då det har varit problem med med SLs API på sista tiden.
