### ISSUE TITLE
Can't get traffic status

### ISSUE THREAD

**Issue by lerra** [hasl-sensor/integration#55]
Hi, I am getting this in my logs,

`ERROR (MainThread) [custom_components.hasl3.slapi] SLAPI_API_Error 1005: Key exists but is not for requested API (Traffic Status)`

I have been trying to recreate the sensors, I am using the "SL Trafikläget 2" key but also tried to use SL "Störningsinformation 2" with the same result, I updated to the latest version of hasl-sensor and still getting the same error, I have been putting quite some time into this and I am stuck now, the key works if I test with https://api.sl.se/api2/trafficsituation.json?key=<my api key>

Any idea?

**Comment by DSorlov** [comment]
This is a configuration error,
