### ISSUE TITLE
SLAPI_API_Error 5322: None (Departure Board)

### ISSUE THREAD

**Issue by PerJarlemark** [hasl-sensor/integration#61]
I started to get this Error about 2023-08-23 and the sensors are not updated anymore

```
Logger: custom_components.hasl3.slapi
Source: custom_components/hasl3/slapi/slapi.py:176
Integration: Svensk Kollektivtrafikssensor (HASL) (documentation, issues)
First occurred: 08:34:41 (229 occurrences)
Last logged: 18:18:29

SLAPI_API_Error 5322: None (Departure Board)
```
Home Assistant 2023.7.2
Supervisor 2023.08.1
Operating System 10.3

**Comment by grobius** [comment]
+1 

System info:

Home Assistant 2023.8.4 (also on 2023.8.3)
Supervisor 2023.08.1
Operating System 10.5

**Comment by Fredaikis** [comment]
Seems like this is an issue on the SL API side, getting the same when requesting the data from the API directly:

`{
    "StatusCode": 5322,
    "Message": "Could not retrive information for buses, trains, trams or metro.",
    "ExecutionTime": 127,
    "ResponseData": {
        "LatestUpdate": "0001-01-01T00:00:00",
        "DataAge": 0,
        "Metros": [],
        "Buses": [],
        "Trains": [],
        "Trams": [],
        "Ships": [],
        "StopPointDeviations": []
    }
}`


See http://status.trafiklab.se/2412460

**Comment by PerJarlemark** [comment]
It seems the API is still having issues
found a thread on their site discussing the issue and why this old API not beeing replaced yet

https://support.trafiklab.se/org/trafiklabse/d/frekvent-felmeddelande/

Also the status page show it's been down for some time now
http://status.trafiklab.se/2412460

**Comment by DSorlov** [comment]
Not a HASL error =(
