### ISSUE TITLE
SL Departure Sensor : '<' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by Joakim-T** [hasl-sensor/integration#64]
Keep getting this error every other refresh:
Api result
'<' not supported between instances of 'int' and 'NoneType'

Would say it happens 50% of the time.

Using SL Departure Sensor
Sensor primary property: min
Refresh: 300
Time: 20
Direction: 1

**Comment by DSorlov** [comment]
Need more context, is it in the logs or gui? what line and so on?
