### ISSUE TITLE
Can't use new SL Deviations

### ISSUE THREAD

**Issue by mickemartinsson** [hasl-sensor/integration#67]
SL Deviations is the new API regarding deviations on SLs transport network. This API replaces the older [Service Alerts (Störningsinformation)](https://www.trafiklab.se/api/trafiklab-apis/sl/service-alerts-2/) and [Traffic Status (Trafikläget)](https://www.trafiklab.se/api/trafiklab-apis/sl/sl-traffic-status-2/) APIs.
The SL Deviations can not be used in HASL-sensor (still wants older APIs).

**Comment by NecroKote** [comment]
Hey @mickemartinsson !
Thanks for reporting this. 
There is pre-release version of this integration that has support for new SL Deviations - check it out! [v3.2.0b2](https://github.com/hasl-sensor/integration/releases/tag/v3.2.0b2)
