### ISSUE TITLE
Questions about settings

### ISSUE THREAD

**Issue by labaland** [hasl-sensor/integration#72]
What are theese 3 doing? :) 
<img width="140" alt="image" src="https://github.com/hasl-sensor/integration/assets/20958435/ef64d71c-efb2-42d5-a4f2-631cc706867b">

And Direction settings is not working i guess?

Tack för bra integration! :)

**Comment by rasssta** [comment]
AFAIK it decides what the state of the sensor should represent. Either minutes, time or when it was last updated. Minutes seems to be the most logical thing to use here.
