### ISSUE TITLE
Changing the refresh timers does not get saved

### ISSUE THREAD

**Issue by systemcrash** [hasl-sensor/integration#73]
The default of 300 is always applied. If I set it to e.g. 1800, it immediately resets to 300. 

Does anyone else experience this?

**Comment by velodromen** [comment]
Yes, this is AFAIK not fixed. It's mentioned in a few other previous issues, e.g. https://github.com/hasl-sensor/integration/issues/51 

There Jontepontelinde mentions: _"I have the exact same situation. To change a value, I need to delete and recreate the integration with the updated number."_

I haven't tried that workaround yet but will give it a go.

**Comment by NecroKote** [comment]
This is fixed since the [v3.2.0b0](https://github.com/hasl-sensor/integration/releases/tag/v3.2.0b0)
