### ISSUE TITLE
Anväder folk denna HACS fortfarande?

### ISSUE THREAD

**Issue by ledyr-sthlm** [hasl-sensor/integration#76]
Hej 
Jag försöker implementera detta, å det vore ju fantastiskt om det går. men för varje steg jag följer i dokumentationen går jag på nitar.
SL platsuppslag längen ger 404
Lägga till Resouces i RAW varnar den för
Är det någon som kan dela hur ni gör i en uppdatera HA?
Tacksam för hjälpen

**Comment by frli4797** [comment]
Många av api'erna som denna integration använder har gått ur tiden.
[NetoKote/trafiklab-sl](https://github.com/NecroKote/trafiklab-sl) är en fork som fungerar rimligt väl och använder SLs nyare endpoints.

**Comment by delize** [comment]
Jag har använt det här repositoriet i flera månader, det fungerade utmärkt fram till för ungefär en månad sedan.

@frli4797 – hur använder du trafiklab-sl i HA?

**Comment by frli4797** [comment]
Jag kör ett enkelt card `type: custom:hasl4-departure-card` för att visa nästa avgång för nårgra linjer nära där jag bor. Den hämtar från ett par olika entities 
`entities:
  - sensor.sl_traffic_xyx
  - sensor.sl_traffic_zzzvagen`

Både hasl-integration och departure-card är från det uppdaterade repot jag nämnde ovan. Det jag fått funka i den fork'en av hasl-integration är `SL Trafik Departures` och `SL Trafik Status` som båda är implementationer av SLs nyaere APIer. 

Om du inte bytt ut dina gamla integration via *detta* repo till repo't angivet ovan så är det första steget. Du kan enkelt lägga till den nya fork'en som ett custom repository i HACS. 

<img width="518" alt="image" src="https://github.com/user-attachments/assets/32b54b85-57e3-4585-8b0d-5492e1661236">

**Comment by delize** [comment]
Ah, jag menade installationen? Laddade du in det i HA via Custom Store, eller använder du ett bibliotek som anropar det, eller ett anpassat Python-skript?

Jag ser bara de förvalda/standardalternativen som en del av den nuvarande integrationen.

Ursäkta om min svenska inte är helt korrekt, det är inte mitt första språk.

**Comment by frli4797** [comment]
Börja med att ta en backup. :)  Ta sedan bort den gamla hasl-integration och card. Gå till HACS och lägg till de nya repon (NecroKote) som "custom repositories" i HACS. Du kommer behöva lägga till URLen för integrationen och kortet separat.  När du gjort det så kommer du kunna installera versionerna från NecroKotes fork. De "vanliga" (HASL) kommer finnas för nedladdning också så det gäller att välja att installera den nya versionen. 
<img width="425" alt="image" src="https://github.com/user-attachments/assets/86465aa0-748f-4cbc-948a-8df8025ca727">
<img width="425" alt="image" src="https://github.com/user-attachments/assets/2e3b6a0e-eb67-4a5b-8176-6b161e2eaecb">

**Comment by delize** [comment]
Ah, använder det som ett HACS-plugin. Låter bra. Har gjort det tidigare, så jag får se hur det går vid uppgraderingen. :) Tack!

**Comment by delize** [comment]
For reference, the correct repos to use are:

Departure Card: https://github.com/NecroKote/HA-hasl3-departure-card
Integration: https://github.com/NecroKote/HA-sl-integration

For a while, I was trying to connect: https://github.com/NecroKote/trafiklab-sl - which didn't have the layout set up correctly

**Comment by ledyr-sthlm** [comment]
Toppen vad kul, och tack för hjälpen. Ska installera detta i veckan!

Den lör 7 dec. 2024 kl 12:30 skrev Andrew Doering ***@***.***

**Comment by ostbergjohan** [comment]
tack @delize Jag har problemet att det bara visas 3 avgångar nån annan som har det eller vet hur man löser?

**Comment by delize** [comment]
@ostbergjohan on the departure card? For what it is worth, I only set it up a few days ago but... I have that problem mainly for buses. 
<img width="556" alt="Screenshot 2024-12-10 at 5 38 42 PM" src="https://github.com/user-attachments/assets/26fa6082-7d12-46ba-9b9d-74cfc91f3935">

<img width="557" alt="Screenshot 2024-12-10 at 5 38 53 PM" src="https://github.com/user-attachments/assets/26885f6d-82ce-42ac-8713-3633f3a0a493">

I just assumed that was all that was being shown for the route? 


But if the above shows more than 3, you should be able to increase the number on "Maximum departures to show" under neath "show transport icon".
<img width="505" alt="Screenshot 2024-12-10 at 5 39 36 PM" src="https://github.com/user-attachments/assets/5fc129d0-3322-47fa-9975-cd3af292cd42">

**Comment by ostbergjohan** [comment]
![image](https://github.com/user-attachments/assets/6258481a-2ebc-40ec-886e-9d52f69b71ab)
The problem is it only showing 3 should be more  atleast 5 right now according to sl.se

**Comment by delize** [comment]
Honestly don't know @ostbergjohan, not the dev or maintainer. My only guess it that SL is only responding with 3 items in the API even if more buses are running. You can check on TrafficLabs and their API.

**Comment by NecroKote** [comment]
Hey everyone! Thanks for using this integration! 
It's been some time since it got any attention, but hopefully, we can change it moving forward.

Considering that we are in the middle of migrating to a new SL API, can somebody summarize what is the current issue being discussed here? Something about the number of departures not displaying correctly on the "new"departure card ?

**Comment by ostbergjohan** [comment]
@NecroKote yeah for me the card only shows the first 3 departures, just did a manuel get from the api and it shows 6 departures but card only show 3  right now.

**Comment by NecroKote** [comment]
@ostbergjohan looking at this https://github.com/hasl-sensor/integration/issues/76#issuecomment-2535849234
I conclude that the issue is not within the card that you're using, but in the sensor configuration itself. 
Can it be that you have some transport type, lane, direction or "forecast duration" filter setup ?

Can you please share your configuration ?

**Comment by ostbergjohan** [comment]
![image](https://github.com/user-attachments/assets/a37b026c-7b9c-49af-96ed-d2cfac0c2a21)
seems like the sensor only gets data for 30 minutes.

**Comment by NecroKote** [comment]
Can you please update the 60 minutes to something like 59 to see if it makes a difference ?

**Comment by NecroKote** [comment]
It appears that the underlying API has a very weird limitation:
<img width="604" alt="image" src="https://github.com/user-attachments/assets/afe2fe37-4855-4a9e-931c-417400999795" />
